/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battle;

/**
 *
 * @author valen
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        visualizzaHelp = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nathan's Adventure: Combattimento: Help\n");
        setResizable(false);

        visualizzaHelp.setEditable(false);
        visualizzaHelp.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        visualizzaHelp.setText("\n- Utilizza \"Pugno\" per infliggere danni al nemico;\n\n- Utilizza \"Schiva\" per poter evitare i colpi del nemico;\n\n- Utilizza \"Inventario\" per poter selezionare un'arma da equipaggiare;\n\n- Utilizza \"Equipaggia\" per poter equipaggiare l'arma selezionata dall'inventario;\n\n- Utilizza \"Attacca con Arma\" per poter attaccare il nemico con l'arma selezionata;\n\n- Per poter utilizzare un arma è necessario prima selezionarla dall'inventario e\n  successivamente premere \"Equipaggia\".");
        jScrollPane1.setViewportView(visualizzaHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane visualizzaHelp;
    // End of variables declaration//GEN-END:variables
}
